sudo: required

language: ruby

services:
  - docker


before_install:
  - sudo apt-get update
  - apt-get update -qq && apt-get install -y nodejs postgresql-client
  - docker-compose build

script:
 - docker-compose -f docker-compose.yml run
